# SPDX-License-Identifier: Apache-2.0
# Copyright 2026 Sander Striker
"""The handover format between the extractor and the engine.

`to_records` is the one place where the extractor's dict-of-entries becomes the
array-of-objects that internal/catalog reads, so the field names and shapes are
worth pinning down. internal/catalog/testdata/catalog.json is generated by this
same function and read back by a Go test, which keeps both sides honest.
"""
import json
from pathlib import Path

from brickmesh_extract.build import to_records

SAMPLE = {
    "32523": {
        "part": "32523",
        "title": "Technic Beam 3",
        "holes": [[0, 0, 0, 0, 1, 0, 0], [20, 0, 0, 0, 1, 0, 0]],
        "pins": [],
        "axle_holes": 0,
    },
    "3673": {
        "part": "3673",
        "title": "Technic Pin",
        "holes": [],
        "pins": [[0, 0, 0, 1, 0, 0, 0]],
        "axle_holes": 0,
    },
    "3001": {
        "part": "3001",
        "title": "Brick 2 x 4",
        "holes": [[0, 0, 0, 0, 1, 0, 0]],
        "pins": [],
        "axle_holes": 0,
    },
}


def test_records_use_the_field_names_the_engine_reads():
    records = to_records(SAMPLE)
    assert isinstance(records, list)
    beam = next(r for r in records if r["id"] == "32523")
    # `id`, not `part`: the Go side decodes into a struct tagged "id".
    assert set(beam) == {"id", "title", "tier", "holes", "pins"}
    assert beam["title"] == "Technic Beam 3"
    assert beam["tier"] == 1


def test_ports_stay_seven_wide_and_numeric():
    for record in to_records(SAMPLE):
        for row in record["holes"] + record["pins"]:
            assert len(row) == 7, "the engine decodes each port as [7]float64"
            assert all(isinstance(v, float) for v in row)


def test_tier_filtering_drops_the_exotic_parts():
    ids = {r["id"] for r in to_records(SAMPLE, max_tier=1)}
    assert ids == {"32523", "3673"}      # the plain brick is tier 3
    assert {r["id"] for r in to_records(SAMPLE, max_tier=3)} == set(SAMPLE)


def test_parts_without_ports_are_dropped():
    cat = {"empty": {"part": "empty", "title": "Technic Beam 3",
                     "holes": [], "pins": [], "axle_holes": 0}}
    assert to_records(cat) == []


def test_records_are_ordered_so_the_output_is_reproducible():
    ids = [r["id"] for r in to_records(SAMPLE)]
    assert ids == sorted(ids)


def test_output_is_json_serializable():
    # numpy scalars would serialize fine here but break json.dump in build().
    json.dumps(to_records(SAMPLE))


def test_the_go_fixture_matches_what_this_function_produces():
    """The fixture the Go test reads is generated from this sample, so if the
    format changes on either side, one of the two suites fails."""
    fixture = Path(__file__).resolve().parents[1] / "internal" / "catalog" / "testdata" / "catalog.json"
    assert fixture.is_file(), f"missing fixture: {fixture}"
    assert json.loads(fixture.read_text()) == to_records(SAMPLE)
